from pydantic import BaseModel, Field

class AskRequestSchema(BaseModel):
    query: str

class AskResponseSchema(BaseModel):
    "Schema representing the RAG system's response to a given question, containing the generated content and the source document name."

    answer: str = Field(description="Answer generated by the language model")
    document_name: str = Field(
        description="Name of the source file from which the context was retrieved"
    )
